version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      
      - pip3 install -r tests/requirements.txt
      - pip3 install pytest
      - pip freeze
      - mkdir test-reports
  build:
    commands:
      - python pytest -v tests/ --junitxml=tests/junit.xml  
      - python pytest --cov
      
      

reports:
  pytest_reports:
    files:
      - junit.xml
    base-directory: tests
    file-format: JUNITXML 
 

 

