version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      
      - pip3 install -r tests/requirements.txt
      - pip3 install pytest
      - mkdir test-reports
  build:
    commands:
      - python - pytest -v tests/ --junitxml=tests
      - python - pytest --cov
     
  post_build:
    commands:
      - echo Build completed on `date`
  

 

