version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      
      - pip install --upgrade pip
      - pip install -r tests/requirements.txt
      - pip install pytest-cov

      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      - python - pytest -v tests/test_func.py
      - python - pytest --cov
  

 

