version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      
      - pip3 install -r tests/requirements.txt
      - pip3 install pytest
      - mkdir test-reports
  build:
    commands:
      - py -3.8 -m pytest -v tests/ --junitxml=tests/junit.xml  py -3.8 -m pytest
      - py -3.8 -m pytest --cov
      

reports:
  pytest_reports:
    files:
      - junit.xml
    base-directory: tests
    file-format: JUNITXML 
 

 

